### ISSUE TITLE
recording error

### ISSUE THREAD

**Issue by jamesshao8** [introlab/odas_web#10]
I am using odas web release 0.1 and respeaker v2.0. I can track sound source, but when I was trying to record, I always get Javascript error.

![wechatimg853](https://user-images.githubusercontent.com/17997195/39998989-54a38d42-57ba-11e8-8360-509435007c96.jpeg)
![wechatimg848](https://user-images.githubusercontent.com/17997195/39998991-55da7b4e-57ba-11e8-9637-2bf657be6557.jpeg)

**Comment by jamesshao8** [comment]
Thanks. I tried your setup procedure and now I am able to compile and run the latest version. but I still can't record the audio files normally. They are all 44Bytes in size and their durations are either 0s or -1s.
![2](https://user-images.githubusercontent.com/17997195/40033731-3797cac2-57e9-11e8-91af-c125e28110d7.png)

**Comment by jamesshao8** [comment]
I think this was a configuration problem. I tried with respeaker mic array v1.0 using similar cfg file from another thread. I can now record to wav files. But with respeaker mic array v2.0 I still can't. 

the cfg file I used for v2.0 is at https://github.com/respeaker/usb_4_mic_array/blob/master/odas.cfg

**Comment by GodCed** [comment]
With an array as small as the respeaker, some tuning may be required in order to obtain a good separation. I'll add @FrancoisGrondin to the conversation as he's more aware of the configuration details.

What would you recommend experimenting with @FrancoisGrondin ?

**Comment by jamesshao8** [comment]
Thanks. I have some other questions: What does post filtered and separated mean and when should I hit the button "determine if separated audio is recorded"?

**Comment by FrancoisGrondin** [comment]
@jamesshao8

Hi,

> I still can't do like in your youtube video to seperate several voices

First, are you able to track multiple voices with the system? If so, how far apart in degrees are the sources? Can you share some separated/postfiltered samples? In the video we used the DGSS separation algorithm, which usually performs better than DDS, but may be unstable if not setup properly.

**Comment by jamesshao8** [comment]
Yes, I am able to track multiple voices. I can see different sources on Active sources locations. I think 2 sources will converge when they are less than around 40 degrees apart. But if the angle separation is larger than that, the tracking is quite precise. I will record the separated/postfiltered samples. But I still don't know what does that mean? So if I use 2 cell phone to play music at the same time. How many wav files should the odas studio produce if it's configured properly?

**Comment by jamesshao8** [comment]
When I do the recording should I hit the "determine if separated audio is recorded" button?

**Comment by jamesshao8** [comment]
I just tried to record from 2 cell phone playing music placed the on the desk, with an angle of 180 degree apart, and the "determine if separated audio is recorded" checked. I can now hear 2 separated music in those files that end with "pf".

**Comment by GodCed** [comment]
Yes, you must hit the « determine if... » button as it enables the recording function (no recording will be produced if the box is unchecked).

Regarding separated and post filtered:
Separated is the output of the separation module, which core is a beam forming algorithm. The files ends with sp.

Post filtered is the output of the post filtering module. It applies filters to the separated audio to enance the separation, but introduce audible artefacts in the stream. The files end with pf.

**Comment by GodCed** [comment]
Also, the system should produce a file set for each source. With two phones, you should get two set (4 files, 2 sp, 2 pf).

Note that if the music stops on one of them, and then restarts, this will stop the first recording set and start a new one.

**Comment by jamesshao8** [comment]
Yes, now I get the separated files, 2 sp and 2 pf, exactly as you said. the pf files do have better separation than sp files, and have some artefacts. 

[2phone_180_degree.tar.gz](https://github.com/introlab/odas_web/files/2007388/2phone_180_degree.tar.gz)

I am uploading my record here, in case some one else would like some references.

And this is how I place my cell phones and the respeaker.
![0516_1](https://user-images.githubusercontent.com/17997195/40094430-f57e56a4-5894-11e8-9592-6ddb12d8b236.jpg)

I think this issue is almost closed.

But I have another question, now the beamforming algorithm is automatically targeted at the DOA of sound sources. If it's possible that I can determine manually which angle I want to record in odas_web? Can I modify the odas_web to achieve that or do I need to modify the c++ code of odascore?

**Comment by GodCed** [comment]
No code modification is needed. You can specify a static tracked source in the ODAS configuration file.
Please see [this issue](https://github.com/introlab/odas/issues/13).

**Comment by jamesshao8** [comment]
Great! I will try that configuration file. Many thanks.

Later today, when I hit the delete all button, after a while I will get a javascript error saying it can't find some file... and sometimes I found files have been recorded even if I didn't check "determine if" box. I am thinking this could be a multi thread problem. will confirm that and get back to you later on.

**Comment by yesheysamang** [comment]
@jamesshao8 I have the same issue that you had regarding the recorded audio files being 44Bytes in size and their durations are either 0s or -1s.  DId you end up solving this issue for the mic array v2.0?  If so how?

**Comment by jamesshao8** [comment]
@yesheysamang Yes, mic array v2.0 can also record wav files successfully now. You need to modify the config file little bit. 

just change line 293 294 307 308 in your config file according to my config file I used for mic array v1.0

Then run odas_web and odascore separately.

    interface: {
        type = "socket";
        ip = "127.0.0.1";
        port = 10000;
    }        

    interface: {
        type = "socket";
        ip = "127.0.0.1";
        port = 10010
    }

**Comment by jamesshao8** [comment]
@GodCed 
Hello GodCed,

I am trying to record sound in a fixed direction. So I set to static mode in sst block. But I found I am unable to record any sound. If, in stead, I firstly set sst block to dynamic and start recording in odas_web, then switch the sst block in static mode and restart the odas_live, then I am able to record sound. I wonder if it is a bug of odas_web? But the recording still doesn't show a beamforming result.

**Comment by GodCed** [comment]
@jamesshao8 

> If, in stead, I firstly set sst block to dynamic and start recording in odas_web, then switch the sst block in static mode and restart the odas_live, then I am able to record sound.

Recording must me enabled in ODAS Studio before the source you want to record appears. For static sources, this means that the record window must be open with the record checkbox checked before you launch ODAS.

> But the recording still doesn't show a beamforming result

I'm not sure I understand what you mean by that. Is it that the recorded audio doesn't seem to match the expected result of a beam former in the specified direction? If that's the case, I'll suggest you refer to the ODAS repo, as ODAS Studio doesn't perform any processing on the incoming audio stream.

**Comment by Texas-C** [comment]
@GodCed 
I tried clicked checkbox and opened recording dialog before recording. But still can not recording in static dircetion. The only way to record in fixed direction is run odas_live in dynamic dircetion(and recording on) before load static direction configure file. Is it a bug O.O? like @taospartan says: "I think odas web is waiting for the audio source to disappear which it won’t do as it’s static, before it writes a file. That’s why it works under dynamic" (https://github.com/introlab/odas/issues/13)

**Comment by jamesshao8** [comment]
@GodCed Thanks GodCed. After following your instruction, we are now able to see the beamforming effect in odas_web. I think beam former result is more obvious in the pf file than in the sp file, but according to my knowledge, all beamforming should be done in sp... I will refer to ODAS repo for the processing.

**Comment by GodCed** [comment]
@jamesshao8
Glad to hear that. 

For the beam forming, the beam former (separation) and the post filtering work together. As the beam former isn’t perfectly « square cut » as in « there a transition period between full gain and full attenuation » , the post filtering remove some more unwanted energy.

That’s why the effect is more obvious after the post filtering. The side effect is some distortion, which can be problematic for some use case. That’s why both audio streams are available.
