### ISSUE TITLE
npm installation error

### ISSUE THREAD

**Issue by auvilink** [introlab/odas_web#11]
Hi, folks, great work.

I have issue running npm install:

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.9.1/node-v64-linux-arm-glibc.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.9.1 and node@10.1.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.10.0/node-v64-linux-arm-glibc.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.10.0 and node@10.1.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 

I have nodejs version 10.1.0 installed.

Thanks.

**Comment by buitre-buitaker** [comment]
Same error here..... how can we setup node to run ODAS? Thank you

**Comment by buitre-buitaker** [comment]
OK, working with node 8... Just downgrade and it runs. Thank you!
