### ISSUE TITLE
Taking recorded wav as input makes the odas_web extremely slow

### ISSUE THREAD

**Issue by ljhao1993** [introlab/odas_web#13]
Hi 
When I take a recorded 8-channel wav file as input of odas and want to look at the potential and tracking information graphically, it makes odas_web run extremely slow, taking several seconds for each frame refreshing and the connection quickly got closed.  The CPU usage is very high (> 90%) while running.

I wonder whether odas_web supports taking wav file as input signals, or is there any way to make odas_web run as normal as taking soundcard signal as input

**Comment by GodCed** [comment]
When ODAS processes from a raw file, it runs as fast as possible, not in real time. Doing so, it outputs the data at a really fast rate and the interface can’t follow. It also quits once the file is over.

I know there was once a function in ODAS to run at « real » speed from a raw file, but I think it’s been refactored away.

You could check with François in the ODAS repo.

**Comment by ljhao1993** [comment]
OK, Thanks for reply, I have used other plot toolkit to roughly get it done.  Making the interface work is obviously more convenient and clear, though.  Maybe I can figure it out later.

Thanks again
