### ISSUE TITLE
High CPU Utilization

### ISSUE THREAD

**Issue by ShingyuKim** [introlab/odas_web#14]
Hello,

First, thank you for this great sound visualization tool!
I have one question about high CPU utilization of the ODAS studio.
Whenever I start it, the CPU utilization jumps to 100% immediately.
I've tested on the Raspberry Pi 3, and on the Windows desktop (Windows7 Enterprise, Intel Core i7-6700, 16GB RAM, GeForce GT730, node v8.11.3, npm v5.6.0, python v2.7.15).
I didn't do anything else just starting the ODAS studio.
Could you help me resolve this issue?
Thank you!

**Comment by GodCed** [comment]
Thanks!

Hmm... That's unusual...
Does it return to normal after say a minute? Is there any error popup or message in the terminal?
