### ISSUE TITLE
Installation Error in MAC OS

### ISSUE THREAD

**Issue by faysalhossain2007** [introlab/odas_web#16]
I am tryig to install ODAS in my MAC OS. But I am geting the followign error:

![screen shot 2018-07-20 at 3 16 34 pm](https://user-images.githubusercontent.com/1239654/43020972-fd2b4f1e-8c2f-11e8-9a8b-8f9e23048526.png)

**Comment by pkalebu** [comment]
did you end up figuring it out? I got the same error

**Comment by faysalhossain2007** [comment]
Yes, I have figured it out.
Check your node and npm version.

**Comment by faysalhossain2007** [comment]
Yes, I have figured it out.
Check your node and npm version.  Try to use node v8.11.3 (which is stable for mac). and npm v5.6.0 which comes with node itself.
Then run npm install and npm start to run ODAS.
