### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by kimchi88** [introlab/odas_web#17]
Hi,
I am trying to follow your instruction to build and install ODAS studio in a Ubuntu 18 virtual machine.
Node version= v10.9.0 and npm version= 6.2.0
After correctly compiling ODAS, I try to install ODAS_WEB by cloning the repositary and launching "npm install" and I get the following error.
Could you please give me a hint?
Thanks!

fse@ubuntu:~/odas_web-0.2-alpha$ npm install

> grpc@1.7.3 install /home/fse/odas_web-0.2-alpha/node_modules/google-gax/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.3/node-v64-linux-x64-glibc.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.7.3 and node@10.9.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.3/node-v64-linux-x64-glibc.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.7.3 and node@10.9.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/home/fse/odas_web-0.2-alpha/node_modules/google-gax/node_modules/grpc/build'
make: Entering directory '/home/fse/odas_web-0.2-alpha/node_modules/google-gax/node_modules/grpc/build'
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
rm: cannot remove './Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o.d.raw': No such file or directory
grpc.target.mk:405: recipe for target 'Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o' failed
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o] Error 1
make: Leaving directory '/home/fse/odas_web-0.2-alpha/node_modules/google-gax/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Linux 4.15.0-29-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/fse/odas_web-0.2-alpha/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/fse/odas_web-0.2-alpha/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc"
gyp ERR! cwd /home/fse/odas_web-0.2-alpha/node_modules/google-gax/node_modules/grpc
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.o
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/fse/odas_web-0.2-alpha/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/fse/odas_web-0.2-alpha/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/fse/odas_web-0.2-alpha/node_modules/google-gax/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
node-pre-gyp ERR! System Linux 4.15.0-29-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/fse/odas_web-0.2-alpha/node_modules/google-gax/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/fse/odas_web-0.2-alpha/node_modules/google-gax/node_modules/grpc
node-pre-gyp ERR! node -v v10.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/home/fse/odas_web-0.2-alpha/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/fse/odas_web-0.2-alpha/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack.o
In file included from ../deps/grpc/src/core/lib/channel/channel_stack.c:19:0:
../deps/grpc/src/core/lib/channel/channel_stack.h:38:10: fatal error: grpc/grpc.h: No such file or directory
 #include <grpc/grpc.h>
          ^~~~~~~~~~~~~
compilation terminated.
grpc.target.mk:405: recipe for target 'Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack.o' failed
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack.o] Error 1
make: Leaving directory '/home/fse/odas_web-0.2-alpha/node_modules/google-gax/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Linux 4.15.0-29-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/fse/odas_web-0.2-alpha/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/fse/odas_web-0.2-alpha/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc"
gyp ERR! cwd /home/fse/odas_web-0.2-alpha/node_modules/google-gax/node_modules/grpc
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.7.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.7.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fse/.npm/_logs/2018-08-16T07_41_17_973Z-debug.log

**Comment by kimchi88** [comment]
EDIT:
I was able to run "npm install" after downgrading node to version 8.
Though, I still have an error when I try to run "npm start":

fse@ubuntu:~/odas_web-0.2-alpha$ npm install

> ODAS_Desktop@0.2.0 postinstall /home/fse/odas_web-0.2-alpha
> electron-rebuild

✔ Rebuild Complete
up to date in 4.436s
fse@ubuntu:~/odas_web-0.2-alpha$ ls
audio-recorder.js  LICENSE       odas.js            README.md      resources    settings.js        views
build.js           main.js       package.json       recordings.js  screenshots  share.js
configure.js       node_modules  package-lock.json  record.js      servers.js   stream-to-text.js
fse@ubuntu:~/odas_web-0.2-alpha$ npm start

> ODAS_Desktop@0.2.0 start /home/fse/odas_web-0.2-alpha
> electron .

/home/fse/odas_web-0.2-alpha/node_modules/electron/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ODAS_Desktop@0.2.0 start: `electron .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ODAS_Desktop@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fse/.npm/_logs/2018-08-16T09_47_29_687Z-debug.log
fse@ubuntu:~/odas_web-0.2-alpha$

**Comment by GodCed** [comment]
Seems like a missing dependency. Try installing the missing package manually with `sudo apt install libgconf-2-4`.

You can also delete the node_modules folder, execute `npm cache clean` then retry the install.

**Comment by kimchi88** [comment]
deleting the node_modules folder and retry to install didn't work.
Instead, installing the missing dependency did the job.
Just want to report that also the libcanberra-gtk-module was missing.

Thanks for your help!

**Comment by GodCed** [comment]
Glad to hear that!
