### ISSUE TITLE
Install odasweb on windows

### ISSUE THREAD

**Issue by zhaoforever** [introlab/odas_web#20]
Hi,
   I'm trying to install odasweb on windows but the installation stops here,
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\adrian\AppData\Local\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\project\Odas\odas_web-0.2-alpha\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\project\Odas\odas_web-0.2-alpha\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at D:\project\Odas\odas_web-0.2-alpha\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\project\\Odas\\odas_web-0.2-alpha\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.8.2" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=grpc_node" "--module_path=D:\\project\\Odas\\odas_web-0.2-alpha\\node_modules\\google-gax\\node_modules\\grpc\\src\\node\\extension_binary\\electron-v1.8-win32-x64-unknown" "--host=https://storage.googleapis.com/" "--remote_path=grpc-precompiled-binaries/node/{name}/v1.7.3" "--package_name=electron-v1.8-win32-x64-unknown.tar.gz"
gyp ERR! cwd D:\project\Odas\odas_web-0.2-alpha\node_modules\google-gax\node_modules\grpc
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1

Error: gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\adrian\AppData\Local\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\project\Odas\odas_web-0.2-alpha\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\project\Odas\odas_web-0.2-alpha\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at D:\project\Odas\odas_web-0.2-alpha\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\project\\Odas\\odas_web-0.2-alpha\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.8.2" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=grpc_node" "--module_path=D:\\project\\Odas\\odas_web-0.2-alpha\\node_modules\\google-gax\\node_modules\\grpc\\src\\node\\extension_binary\\electron-v1.8-win32-x64-unknown" "--host=https://storage.googleapis.com/" "--remote_path=grpc-precompiled-binaries/node/{name}/v1.7.3" "--package_name=electron-v1.8-win32-x64-unknown.tar.gz"
gyp ERR! cwd D:\project\Odas\odas_web-0.2-alpha\node_modules\google-gax\node_modules\grpc
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (D:\project\Odas\odas_web-0.2-alpha\node_modules\spawn-rx\lib\src\index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (D:\project\Odas\odas_web-0.2-alpha\node_modules\rxjs\Subscriber.js:239:16)
    at SafeSubscriber.error (D:\project\Odas\odas_web-0.2-alpha\node_modules\rxjs\Subscriber.js:198:26)
    at Subscriber._error (D:\project\Odas\odas_web-0.2-alpha\node_modules\rxjs\Subscriber.js:129:26)
    at Subscriber.error (D:\project\Odas\odas_web-0.2-alpha\node_modules\rxjs\Subscriber.js:103:18)
    at MapSubscriber.Subscriber._error (D:\project\Odas\odas_web-0.2-alpha\node_modules\rxjs\Subscriber.js:129:26)
    at MapSubscriber.Subscriber.error (D:\project\Odas\odas_web-0.2-alpha\node_modules\rxjs\Subscriber.js:103:18)
    at SafeSubscriber._next (D:\project\Odas\odas_web-0.2-alpha\node_modules\spawn-rx\lib\src\index.js:251:65)
    at SafeSubscriber.__tryOrSetError (D:\project\Odas\odas_web-0.2-alpha\node_modules\rxjs\Subscriber.js:248:16)
    at SafeSubscriber.next (D:\project\Odas\odas_web-0.2-alpha\node_modules\rxjs\Subscriber.js:188:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! ODAS_Desktop@0.2.0 postinstall: `electron-rebuild`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the ODAS_Desktop@0.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

  Would you please provide a new version of X64 odasweb? Thanks.

**Comment by GodCed** [comment]
Sorry, packaging tool broke after adding multiple process so that’s why there’s no new binary avaible.

Try this to add python to npm and retry the installation.
`npm --add-python-to-path='true' --debug install --global windows-build-tools`

**Comment by zhaoforever** [comment]
> Sorry, packaging tool broke after adding multiple process so that’s why there’s no new binary avaible.
> 
> Try this to add python to npm and retry the installation.
> `npm --add-python-to-path='true' --debug install --global windows-build-tools`

**Comment by zhaoforever** [comment]
> Sorry, packaging tool broke after adding multiple process so that’s why there’s no new binary avaible.
> 
> Try this to add python to npm and retry the installation.
> `npm --add-python-to-path='true' --debug install --global windows-build-tools`

Thank you, it works!
Besides it need the administrator rights.
