### ISSUE TITLE
Problem in installation step npm instrall

### ISSUE THREAD

**Issue by PatrickYung** [introlab/odas_web#21]
I was trying to install the odas_web with node version 10.13.0 and npm version 6.4.1

But it is unluck to encounter this problem

May I know what is the solution the settle this problem?

`make: Leaving directory '/home/pi/odas_web/node_modules/google-gax/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.9.19-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/home/pi/odas_web/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/pi/odas_web/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v64-linux-arm-glibc"
gyp ERR! cwd /home/pi/odas_web/node_modules/google-gax/node_modules/grpc
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.9.1 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.9.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-11-01T04_44_41_952Z-debug.log
pi@raspberrypi:~/odas_web $ 
`

**Comment by GodCed** [comment]
I did not test the install on node 10, only node 8. You may want to try downgrading.
Issue #22 mentions overcoming the problem, so you may want to ask for more info there.

**Comment by PatrickYung** [comment]
Thanks, it is working by upgrading to node 8.
