### ISSUE TITLE
Problem running in windows 10 and linux

### ISSUE THREAD

**Issue by gary0351** [introlab/odas_web#22]
I installed nodejs/npm/electron. Got past gyp issue with install.

Windows distribution exe will not bring up web page. It lists ports to monitor on startup and does nothing else.

I set up a web app version of ODAS web using 'npm start' which brings up web page, displays noise and speech sources but hangs on recording. Switched to latest release which does same thing.

Perhaps I missed something when installing nodejs, etc. I reinstalled to make sure.

I set up same code running with ubuntu on virtualBox. It runs and sort of records audio <1 sec.
Which is better OS - win10 or linux or macOS? What was web server developed on?
Any insight would be appreciated.
Attached log files from win execution.
Thanks
Gary
[ms-cmd-prompt.log](https://github.com/introlab/odas_web/files/2539121/ms-cmd-prompt.log)
[2018-11-01T15_06_40_420Z-debug.log](https://github.com/introlab/odas_web/files/2539123/2018-11-01T15_06_40_420Z-debug.log)

**Comment by GodCed** [comment]
Seems like a lot of things are not running smoothly there. I am not a node expert in any way so I can't really pinpoint the problem from your logs.

Pre-compiled release are outdated, so that's that.

Web server was developed on both Mac and Linux. I also ran it on Windows. I don't think there is a "recommended os". Virtual Machines may be underpowered and/or experience problems with WebGL drivers, so I would try to avoid them. I think your problem on Ubuntu is simply that the recorder process can't keep up because system ressources are hoarded by the UI updates (the charts).

My advice would be to try to use Node 8 instead of 10, as it is the Node version the app was developed on and some package seems to not upgrade very well. (Mainly the gyp things)

**Comment by gary0351** [comment]
Cedric,

Appreciate the quick response. I’ll try running with Node8 first.

I asked about the OS thinking that it was developed on a *nix platform. If windows doesn’t work, I’ll set up a dedicated Linux machine or find a mac.

Thanks again.

Gary

**Comment by gary0351** [comment]
Cedric,

Have some questions about ODAS.

Post Filtered and Separated Sources streams have 4 channels interleaved so 8 bytes includes one 16 bit sample in order for each channel. Data stream is Network Byte Ordered (Big Endian). Is that correct?

I adapted the respeaker .cfg file for ODAS running on a respeaker core v2 demo board and it feeds audio to ODAS Web just fine.

I am feeding PF (or  SS) stream to android app using TCP socket and getting poor audio – does not sound like speech at all. Track and other streams currently go to ODAS Web. The app has a receive buffer size of 2048 bytes. I see data input of up to 1448 bytes from ODAS. Channel 0 is extracted from receive buffer to feed audio to another service. I’ll process the other channels when I get this working.

The respeaker and android processors should be adequate for what I want to do.

Do you have suggestions/recommendations to improve audio quality. Are there buffer size changes or other settings in .cfg file that would help? Should the hopsize be set to something else? Current cfg parameters for PF and SS used with ODAS Web and android app are:

    separated: {

        fS = 16000;
        hopSize = 512;
        nBits = 16;

        interface: {
                type = "socket";
                ip = "192.168.1.10";
                port = 10000;
        }

    };

    postfiltered: {

        fS = 16000;
        hopSize = 512;
        nBits = 16;

        interface: {
                type = "socket";
                ip = "192.168.1.14";
                port = 10010;
        }

    };

 I really appreciate any suggestions you might offer.

Thanks,
Gary

**Comment by GodCed** [comment]
> Post Filtered and Separated Sources streams have 4 channels interleaved so 8 bytes includes one 16 bit sample in order for each channel.

Yes, that's right.

> Data stream is Network Byte Ordered (Big Endian).

I'm like 90% sure that is correct. You may want to check the ODAS repo if testing both is time consuming.

> I adapted the respeaker .cfg file for ODAS running on a respeaker core v2 demo board and it feeds audio to ODAS Web just fine.

Good, so we know your config file is properly written.

> I am feeding PF (or  SS) stream to android app using TCP socket and getting poor audio – does not sound like speech at all. Track and other streams currently go to ODAS Web. The app has a receive buffer size of 2048 bytes. I see data input of up to 1448 bytes from ODAS. Channel 0 is extracted from receive buffer to feed audio to another service. I’ll process the other channels when I get this working.

Two things I would check. Sample format that your Android APP accepts, wether it's signed, unsigned or float. Timing with the sample, packets always arrive in order in socket, but they can be "glued" together. As packet 1, 2 then 3 can arrive as 1+2 then 3. Thus, it is important to never discard bytes and to start from the first byte sent by ODAS while parsing.
You may want to take a look at recordings.js and audio-recorder.js for inspiration.

**Comment by gary0351** [comment]
I will follow up on your suggestions.

Thanks again,
Gary

**Comment by gary0351** [comment]
For some reason the ODAS software stops transmitting audio after about 20 seconds. The audio I do get is very clear with low latency. Is there a way to debug what is happening internally?

Attached copy of the config file for reference. Is there some setting that could be terminating the audio transmission?

These are the instructions (https://respeaker.io/6_mic_array/) I followed to build the software for the respeaker board running Debian:
	sudo apt-get install libfftw3-dev libconfig-dev libasound2-dev
	sudo apt-get install cmake
       git clone https://github.com/introlab/odas.git
       mkdir odas/build
       cd odas/build
       cmake ..
       make
       
Recommendations?

Thanks,
Gary

**Comment by GodCed** [comment]
From what I seen in the past, this usually happens when either ODAS cannot process the audio in real time or the receiving end cannot keep up with the incoming data.

ODAS internal or socket buffer fill up and processing stops. I’ll take a look at CPU usage on the machine that’s running ODAS and on the machine receiving audio to see if any of them is saturated.

**Comment by GodCed** [comment]
That was a feature under developpement in ODAS a few months ago, but the granular branch doesn’t exist anymore. I am not aware of the current state of this feature.

You could try to get more info on the ODAS repository.

**Comment by gary0351** [comment]
I can reduce the search volume of the mics to +30 and -20 deg to see how that affects processor loading.

I will also look at the ODAS repository and your papers again.

The potential sources feed the separated sources processing. Are the postfiltered sources used to generate the tracked sources info? If disabled, does it cause other things to fail?

Thanks for your help.
Gary

**Comment by GodCed** [comment]
The processing flow is as follow:  
* Potential feeds tracking
* Tracking and audio feeds separation
* Separation and tracking feeds post filtering

Post filtering is only applied to the separated audio to improve separation. I can be disabled if the resulting audio stream is not used. Tracking is based solely on the potential sources.

**Comment by gary0351** [comment]
Thanks for the info.
Really appreciate your help,
Gary

**Comment by GodCed** [comment]
My pleasure. Feel free to open another issue if you experience other difficulties.
