### ISSUE TITLE
Odas_Web on RPI

### ISSUE THREAD

**Issue by taospartan** [introlab/odas_web#3]
Hi trying to use the odas_web app on the newest version of raspbian with pixel desktop. While the app itself runs, no gui is visible. Any help would be greatly appriciated.

**Comment by GodCed** [comment]
This is a known issue with the latest release of the Electron framework, which is used in ODAS Studio, and Raspbian Stretch. Please see [this thread](https://github.com/electron/electron/issues/10468) for more information.

I'll lock Electron to a previous working version for now, so it should work on the Pi while the Electron folks work on their side.
