### ISSUE TITLE
How can I use odas studio?

### ISSUE THREAD

**Issue by suekiti0327** [introlab/odas_web#30]
Nice to meet you.

I'm  using Respeaker 4 mic array now.
But I can't use odas studio.
I installed node.js and npm in my PC.
I don't know the case.
If you are familiar with how to use it, I want to know the details of the procedure for using it on a PC.

It's bothersome for you, but only for you is for me, I will be nice if you can describe the flow of installing node.js and npm.

Thank you.

**Comment by GodCed** [comment]
Hi @suekiti0327,

You state you have installed node.js and npm but require help with the installation?
What problem are you experiencing so that I can help you resolve the issue?

Did you follow the [ODAS Studio installation instructions](https://github.com/introlab/odas_web#from-sources)?
Did you use node.js v8? It is the required LTS version for ODAS Studio.

**Comment by suekiti0327** [comment]
Hi @GodCed 

For confirmation, I'm glad if node.js and npm can teach you how to install.
Also, I'm glad to share with you the steps after installing them.

When I install node.js and npm and execute npm start as root, I get an npm error.

I was following the installation procedure of odas studio.

I use node.js v8.

That's the answer to your question.

I apologize for the inconvenience, but thank you.

**Comment by suekiti0327** [comment]
![IMG_2484](https://user-images.githubusercontent.com/45155499/57344172-0f203680-7181-11e9-9a4a-6688f5302b06.jpg)
This is the situation when you get an error.

**Comment by GodCed** [comment]
Please see the [node.js installation instructions](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions-enterprise-linux-fedora-and-snap-packages).

`$ node -v` should return v8.

**Comment by GodCed** [comment]
Please see the [node.js installation instructions](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions-enterprise-linux-fedora-and-snap-packages).

`$ node -v` must return v8.

**Comment by GodCed** [comment]
Please see the [node.js instructions](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions-enterprise-linux-fedora-and-snap-packages).

`$ node -v` should return v8.

**Comment by suekiti0327** [comment]
In that case, how should I change the current version?
Could you tell me?
