### ISSUE TITLE
ODAS Studio on Windows

### ISSUE THREAD

**Issue by Fibo27** [introlab/odas_web#32]
Hi 

I have Respeaker 6 mic array for RPi. When i run ODAS Studio on Rpi it is very slow - uses up 98% of CPU and as has been articulated in #14, i have similar issues.

My query: (& sorry if i may appear naive)
How can i run ODAS Studio on Windows with the Respeaker 6 mic array hat connected to the Rpi - is this even possible ? If yes, can you please outline the steps? 

When i run it on Rpi

i do an npm start in the root folder. So what so i need to do in this case

Thanks

**Comment by GodCed** [comment]
Yes you can run ODAS and ODAS Studio on different machines.

First, you must install ODAS Studio on your Windows machine. Then, you must configure ODAS on your Pi to sink to the Windows machine per [those insctructions.](https://github.com/introlab/odas_web#configure-odas) You will need to provide your Windows machine ip and make sure your firewall allow connection on the port used by ODAS.

Finally, you start ODAS Studio on the Windows machine then ODAS on the Pi.

**Comment by Fibo27** [comment]
thanks a lot - i would presume that the ip address of windows machine will be required when we do this - "The Local System Monitor in ODAS Studio displays the computer IP for easy configuration of a remote system."

And the ports are: 9000, 9001, 10000, 10001 - is that correct?

**Comment by Fibo27** [comment]
Hi - if i may and just to make that i understand (sorry i am a new bee so please bear with me!)
For the below instructions, i have some questions - next to the line items:

Installation
From sources
Install Node.js
Install npm
Clone the repository: **Should i clone the repository from here  https://github.com/introlab/odas_web#configure-odas**
Run npm install in root folder : **is this to be done like in the case of Pi?**
From prebuilt package
Download appropriate release for your OS. **Should i download version 0.1 or 0.2**
Extract to the desired location.
Usage
Run npm start in root folder to laumch the app from sources. **Is this done on Pi or Windows?**
Run the executable in the extracted release folder to launch the prebuilt app.**Is this done on Pi or Windows?**

Run ODAS
For remote execution, start ODAS in command line on the distant system. As odascore is a TCP client and ODAS Studio is a TCP server, ODAS Studio must be started before odascore. **I presume i have to do this in the case of Windows - can you please explain the process?**

Again - thanks for your help in advance - i realize it is a bit of spoon feeding but appreciate your help.

**Comment by GodCed** [comment]
To run ODAS Studio on Windows, you just have to repeat the exact same steps you performed to have it running on the PI.

The only steps you have to perform on the PI is to configure and run ODAS. Yes you will need to specify your windows machine IP in the ODAS configuration file. The ports are correct.
