### ISSUE TITLE
How to set arecord -L

### ISSUE THREAD

**Issue by suekiti0327** [introlab/odas_web#35]
The respeaker / seeed-voicecard shows how to use respeaker 4mic, but there are some differences when I use it.
The following picture is that part.
![IMG_2616](https://user-images.githubusercontent.com/45155499/59812710-dc558a80-9349-11e9-8eb8-c0b5808ee97d.jpg)

The instruction manual is displayed as follows.
![IMG_2617](https://user-images.githubusercontent.com/45155499/59812804-3b1b0400-934a-11e9-8cb7-b145654e7822.jpg)

In this case, what should I do?
Thank you.

**Comment by GodCed** [comment]
This is not an issue with ODAS Studio, please refer to the [Seeed Voicecard repo](https://github.com/respeaker/seeed-voicecard/issues).
