### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by satell** [introlab/odas_web#6]
Hi after runing following command in Ubuntu 
npm install

I got: 

npm WARN lifecycle ODAS_Desktop@0.2.0~postinstall: cannot run in wd %s %s (wd=%s) ODAS_Desktop@0.2.0 electron-rebuild /home/user/Desktop/odas/odas_web

and then wen I run: 
start npm 

I get 

start: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused

please help me to solve this issue 

Best regards 
Ehsan

**Comment by GodCed** [comment]
Hello, which Ubuntu and Node version are you using? I wouldn't recommend using a Node version prior to 8.

You can view your Node version by running `node -v` from a terminal.

**Comment by satell** [comment]
I use these versions :
``root@user-LIFEBOOK-S752:/home/user/Desktop/odas/odas_web# node -v
v8.11.1
root@user-LIFEBOOK-S752:/home/user/Desktop/odas/odas_web# npm -v
5.6.0

**Comment by GodCed** [comment]
Sorry about the long delay, I was quite busy on my side. If you haven’t figured this out, did you run npm install as root or with sudo? If so, the post install script that rebuilds the packages for electron will probably fail, giving you this error.
