### ISSUE TITLE
wav with seperated sources

### ISSUE THREAD

**Issue by tigaworx** [introlab/odas_web#9]
Hi, instead of a real issue I merely have a question. I hope that is okay. (Please tell me if there is a better way to ask questions.)
My question: If a have two sound sources can I get separated wav files for both sources? One wav per source? When I tested this, I indeed got two wavs of separated sources, but one of them was empty. It seems like the algorithm only records the loudest source properly...

**Comment by GodCed** [comment]
Normally, there is an audio file created for each source. I experienced empty files when recording really short burst of sound. It’s currently a limitation of the system because of the way the tracking and separating modules operate in ODAS.

**Comment by tigaworx** [comment]
Yes thank you! Short burst of sound must have been my problem. One of the sources was counting and there was a short pause after each number. When we tested again with fluent text it worked fine.

**Comment by yesheysamang** [comment]
@tigaworx are you using respeaker mic array v1.0 or the 2.0?  If it is the 2.0 would you mind sending your config file.  I cant seem to record correctly, thanks.
